name: setup java
on: 
  workflow_call:
    inputs:
      java_ver:
        default: '17'
        description: Input the desired java version to be setup
        type: string
jobs:
  jdk:
    name: setup java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' 
          java-version: ${{ inputs.java_ver }}
      - run: echo test
